# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="eastwood"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
COMPLETION_WAITING_DOTS="true" # I do not know what this does.

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    docker 
    git
    golang
    kubectl
    rust
    sudo
)

source $ZSH/oh-my-zsh.sh

source ~/antigen.zsh

alias ls='ls -C -F -G'
alias ll='ls -l'
alias la='ls -a'

alias zrc='cd ~ && nvim .zshrc'
alias nrc='cd ~/.config/nvim && nvim init.lua'
alias codef='cd ~/Code'

source ~/.zsh/catppuccin_macchiato-zsh-syntax-highlighting.zsh
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

path+="$HOME/go/bin"

typeset -U path

